### ISSUE TITLE
more info about this repository

### ISSUE THREAD

**Issue by abubelinha** [gbif/collection-mobilization#1955]
Hi.  I have just found this repository but the README information is pretty obscure to me.

> used to coordinate data mobilisation based on [GRSciColl](https://www.gbif.org/grscicoll)  entries.

What does that mean?
I wonder if this is about correcting wrong information in those entries.

If that is the case, I am also wondering to which extent the info in those entries is kept synchronized with other sources (in order to know which info should preferrably be submitted to the original sources and/or to GRSciColl). 
From [GRSciColl data sources and maintenance](https://www.gbif.org/grscicoll):
> GBIF is working with partners to establish a standardized, interoperable flow of information between this registry and other key collections infrastructures. GRSciColl runs a weekly synchronization with [Index Herbariorum](http://sweetgum.nybg.org/science/ih/) (IH).

For example, I would like to know which parts of the IH information are being used. 
I think this [IH issue](https://github.com/nybgvh/IH-API/issues/6) is related and I would like to hear opinions about that suggestion.

Thanks!
@abubelinha

**Comment by ManonGros** [comment]
Hi @abubelinha
Each issue in this repository correspond to an institution in GRSciColl. Our Asian and African support teams are going through those issues and evaluate whether the institution information is up to date and whether there any occurrences for specimens hosted by the institution on GBIF.
We have two goals here:

- tidy up GRSciColl as much as possible
- identify institutions who might be interested in sharing (more) occurrences on GBIF and offer them support to do so

You can click on any issue and see the workflow my colleagues follow. You can also check our wiki pages: https://github.com/gbif/collection-mobilization/wiki
The work is in progress and the workflows are evolving are we learn more.

Right now we are focusing only on African and Asian institutions.

When it comes to documenting which GRSciColl fields are synchronised with IH, you can check this GitHub original issue: https://github.com/gbif/registry/issues/167. We have since then made a few modifications to the original model described there as we changed the way we work with contacts and a few minor other modifications documented in our registry repository: https://github.com/gbif/registry/issues?q=is%3Aissue+is%3Aclosed+IH.

I will close this issue. Let me know if it needs to be reopened.
